[package]
name = "dockwatch"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "dw"
path = "src/main.rs"

[dependencies]
bollard = "0.19.4"
clap = { version = "4.5.51", features = ["derive"] }
futures-util = "0.3.31"
tokio = { version = "1.48.0", features = ["full"] }

